---
title: "Projekt zaliczeniowy"
author: "Ksenia Kvitko"
date: "26 06 2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

# 1. Ładowanie bibliotek
```{r, results = 'hide', warning=FALSE, message=FALSE}
library(DESeq2)
library(ggplot2)
library(ComplexHeatmap)
```

# 2. Informacje o danych bioprojektu (PRJNA313294)
```{r, warning=FALSE, message=FALSE}
SRAruns <- c("SRR3191542", "SRR3191543", "SRR3191544", "SRR3191545", "SRR3194428", "SRR3194429", "SRR3194430", "SRR3194431")
SRAitems <- c("Mock1-1", "Mock2-1", "ZIKV1-1", "ZIKV2-1", "Mock1-2", "Mock2-2", "ZIKV1-2", "ZIKV2-2")
SRAdevices <- c(rep("Illumina MiSeq", times = 4), rep("Illumina NextSeq 500", times = 4))
SRAshortcuts <- c("Mock_1_MiSeq", "Mock_2_MiSeq", "ZIKA_1_MiSeq", "ZIKA_2_MiSeq", "Mock_1_NextSeq", "Mock_2_NextSeq", "ZIKA_1_NextSeq", "ZIKA_2_NextSeq")

SRAdata <- rbind(SRAruns, SRAitems, SRAdevices, SRAshortcuts)
print(SRAdata)
```

# 3. Wczytanie danych zmapowanych do genomu hg19
```{r, results = 'hide', warning=FALSE, message=FALSE}
counts_all <- read.delim("~/projekt/analizaTranskryptomu/projekt/hg19/COUNTS/counts_ALL.txt", comment.char="#")
colnames(counts_all)[7:14] <- SRAshortcuts

counts_paired <- read.delim("~/projekt/analizaTranskryptomu/projekt/hg19/COUNTS/counts_PE.txt", comment.char="#")
colnames(counts_paired)[7:10] <- SRAshortcuts[1:4]

counts_single <- read.delim("~/projekt/analizaTranskryptomu/projekt/hg19/COUNTS/counts_SE.txt", comment.char="#")
colnames(counts_single)[7:10] <- SRAshortcuts[5:8]
```

# 4. Analiza DE

```{r, results = 'hide', warning=FALSE, message=FALSE}
dds <- function(data, runs) {
  countData <- data[,7:(7+runs-1)]
  rownames(countData) = data$Geneid
  samples <- names(countData)
  if(runs > 4) {
    condition <- factor(c("mock", "mock", "zika", "zika", "mock", "mock", "zika", "zika"))
  }
  else {
    condition <- factor(c("mock", "mock", "zika", "zika"))
  }
  colData <- data.frame(samples = samples, condition = condition)
  dds <- DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~condition)
  
  return(dds)
}

analyseDE = function(data) {
  dds <- DESeq(data)
  res <- results(dds)
  
  r = res[res$baseMean!=0,]
  r = r[r$log2FoldChange > 1 | r$log2FoldChange < -1,]
  x = !is.na(r$padj)
  r = r[x,]
  r = r[r$padj<0.05,]
  
  print(head(r))
  
  return(dds)
}
```

## 4.1. Zbiorcza
```{r, warning=FALSE, message=FALSE}
DE_all <- analyseDE(dds(counts_all, 8))
```

## 4.2. Dla każdego z urządzeń

### Illumina MiSeq
```{r, warning=FALSE, message=FALSE}
DE_paired <- analyseDE(dds(counts_paired, 4))
```

### Illumina NextSeq 500
```{r, warning=FALSE, message=FALSE}
DE_single <- analyseDE(dds(counts_single, 4))
```

# 5. Analiza PCA
```{r, warning=FALSE, message=FALSE}
PCAnalysis <- function(data, runs) {
  gene_data <- data[7:14]
  rownames(gene_data) <- data$Geneid
  
  row_sub <- apply(gene_data, 1, function(row) all(row != 0))
  gene_data <- gene_data[row_sub,]
  gene_data_matrix <- as.matrix(gene_data)
  
  pca <- prcomp(t(gene_data_matrix), scale = T)
  pca.data <- data.frame(Sample = rownames(pca$x), X = pca$x[,1], Y = pca$x[,2])
  pca.var <- pca$sdev^2
  pca.var.per <- round(pca.var/sum(pca.var)*100, 1)
  
  ggplot(data = pca.data, aes(x = X, y = Y, label = Sample)) +
    geom_text() +
    xlab(paste("PC1 - ", pca.var.per[1], "%", sep="")) +
    ylab(paste("PC2 - ", pca.var.per[2], "%", sep="")) +
    theme_bw() +
    ggtitle("PCA Plot")
  
}

counts_all_display <- counts_all
colnames(counts_all_display)[7:14] <- c("M1_Mi", "M2_Mi", "Z1_Mi", "Z2_Mi", "M1_Next", "M2_Next", "Z1_Next", "Z2_Next")
PCAnalysis(counts_all_display)
```

# 6. Heatmapa
```{r, warning=FALSE, message=FALSE}
normalize <- function(data) {
  log_data <- rlog(data)
  normalized_data<- assay(log_data)
  normalized_data <- as.data.frame(normalized_data)
  
  return(normalized_data)
}

drawHeatmap <- function(data){
  threshold <- 14.5
  data <- data[
      data$Mock_1_MiSeq > threshold | 
      data$Mock_2_MiSeq > threshold | 
      data$ZIKA_1_MiSeq > threshold | 
      data$ZIKA_2_MiSeq > threshold | 
      data$Mock_1_NextSeq > threshold | 
      data$Mock_2_NextSeq > threshold |
      data$ZIKA_1_NextSeq > threshold |
      data$ZIKA_2_NextSeq > threshold
    , ]
  
  Heatmap(data , cluster_columns = FALSE,
          row_names_side = "left",
          row_dend_sid = "left",
          row_names_gp=gpar(cex = 0.8))
}

data_for_heatmap <- normalize(dds(counts_all, 8))
data_reordered <- data_for_heatmap[c(0,1,2,5,6,3,4,7,8)]
drawHeatmap(data_reordered)
```